In [1]:
a = 10
#variable is declared as the value 10 is assigned to it.

In [2]:
#Numerical Data Types in Python
#Integers #Float
#Complex Numbers #Boolean

In [3]:
#Integers are used to represent whole number values.
a = 100
b = 124
#Float data type is used to represent decimal point values.
a = 12.30
#Complex numbers are used to represent imaginary values. Imaginary values are denoted with ‘j’ at the end of the number.
x = 10 + 5j
#Boolean is used for categorical output, since the output of boolean is either true or false.
num = 5 > 4
#num is the boolean variable
type(num)
#the output will be bool
print(num)
#this will print true.

True

In [ ]:
#Checking Data Types
num1 = 5
print(num1, 'is of type', type(num1))

num2 = 2.0
print(num2, 'is of type', type(num2))

num3 = 1+2j
print(num3, 'is of type', type(num3))

a='Hii Python'
print(a, 'is of type', type(a))

a = True
print(a, 'is of type', type(a))

5 is of type <class 'int'>
2.0 is of type <class 'float'>
(1+2j) is of type <class 'complex'>
Hii Python is of type <class 'str'>
True is of type <class 'bool'>

In [ ]:
#Python program to demonstrate fundamental concepts of loops in python
#printig even number between 20 to 1
#using while loop
num=20
print("\n Using while loop")
while(num>0):
  print(num)
  num=num-2
print("\n Using for loop")
#using for loop
for i in range(20,0,-2):
  print(i)

 Using while loop
20
18
16
14
12
10
8
6
4
2

 Using for loop
20
18
16
14
12
10
8
6
4
2

In [ ]:
# Declaring a function
def fun():
    print("Inside function")
fun()
def evenOdd( x ):
    if (x % 2 == 0):
        print("even")
    else:
        print("odd")

# Driver code
evenOdd(2)
evenOdd(3)
# Python program to demonstrate
# default arguments
def myFun(x, y = 50):
    print("x: ", x)
    print("y: ", y)

# Driver code
myFun(10)

Inside function
even
odd
x:  10
y:  50

In [4]:
# Python program to demonstrate Creation of List
List = [10, 20, 14]
print("\nList of numbers: ")
print(List)
# Addition of Elements
List.append(15)
List.append(60)
List.append(45)
# Addition of Element at specific Position (using Insert Method)
List.insert(3, 12)
List.insert(0, 'Hello')
print("\nList after Addition of elements: ")
print(List)
# Removing elements from List using Remove() method
List.remove(60)
List.remove(45)
print("\nList after Removal of two elements: ")
print(List)
# Removing element at a specific location from the Set using the pop() method
List.pop(2)
print("\nList after popping a specific element: ")
print(List)

List of numbers:
[10, 20, 14]

List after Addition of elements:
['Hello', 10, 20, 14, 12, 15, 60, 45]

List after Removal of two elements:
['Hello', 10, 20, 14, 12, 15]

List after popping a specific element:
['Hello', 10, 14, 12, 15]

In [5]:
# Creating a Tuple with Mixed Datatype
Tuple1 = (10, 'Welcome', 20, 'Python')
print("\nTuple with Mixed Datatypes: ",Tuple1)
# Concatenation of tuples
Tuple1 = (0, 10, 20, 30)
Tuple2 = ('Hello', 'Welcome To', 'Python')
Tuple3 = Tuple1 + Tuple2
# Printing Final Tuple
print("\nTuples after Concatenation: ",Tuple3)
#appending elements to tuple3
print("\nTuples after Appending: ",Tuple3 + (3,4,))
# Remove items from a tuple
l = list(Tuple3)
l.remove(0)
Tuple3_remove = tuple(l)
print("\nTuples after Removing item: ",Tuple3_remove)
# Deleting a Tuple
del Tuple1

Tuple with Mixed Datatypes:  (10, 'Welcome', 20, 'Python')

Tuples after Concatenation:  (0, 10, 20, 30, 'Hello', 'Welcome To', 'Python')

Tuples after Appending:  (0, 10, 20, 30, 'Hello', 'Welcome To', 'Python', 3, 4)

Tuples after Removing item:  (10, 20, 30, 'Hello', 'Welcome To', 'Python')

In [6]:
my_dict = { "Name": "Kalyani", "age": 18, "City": "Chh.Sambhajinagar"}
#adding key-value pair
my_dict["Country"] = "India"
print("\n adding key-value pair",my_dict)
#updating key-value pair
my_dict["age"] = 20
print("\n updating key-value pair",my_dict)
#deleting key-value pair
del my_dict["City"]
print("\n deleting key-value pair",my_dict)

 adding key-value pair {'Name': 'Kalyani', 'age': 18, 'City': 'Chh.Sambhajinagar', 'Country': 'India'}

 updating key-value pair {'Name': 'Kalyani', 'age': 20, 'City': 'Chh.Sambhajinagar', 'Country': 'India'}

 deleting key-value pair {'Name': 'Kalyani', 'age': 20, 'Country': 'India'}

In [ ]:
# Basic Calculations
# Calculator Program in Python by using input() and format() functions
#Promting input from the user

num1 = float(input("Enter the First Number: "))
num2 = float(input("Enter the Second Number: "))

#addition

print("{} + {} = ".format(num1, num2))
print(num1 + num2)

#subtraction

print("{} - {} = ".format(num1, num2))
print(num1 - num2)

#multiplication

print("{} * {} = ".format(num1, num2))
print(num1 * num2)

#division

print("{} / {} = ".format(num1, num2))
print(num1 / num2)

Enter the First Number: 10
Enter the Second Number: 20
10.0 + 20.0 =
30.0
10.0 - 20.0 =
-10.0
10.0 * 20.0 =
200.0
10.0 / 20.0 =
0.5

In [8]:
#Calculator Program in python by defining operations.Define Operators or Functions: Addition, Subtraction, Multiplication, and Division
def addition(n1, n2):# Addition
    return n1 + n2
def subtraction(n1, n2):# Subtraction
    return n1 - n2
def multiplication(n1, n2):# Multiplication
    return n1 * n2
def division(n1, n2):# Division
    return n1 / n2
print("Select Operations")
print("1. Addition 2. Subtraction 3. Multiplication 4. Division")
operation = int(input("Enter choice of operation 1/2/3/4: "))
n1 = float(input("Enter the First Number: "))
n2 = float(input("Enter the Second Number: "))
if operation == 1:
    print (n1, "+", n2, "=", addition(n1, n2))
elif operation == 2:
    print (n1, "-", n2, "=", subtraction(n1, n2))
elif operation == 3:
    print (n1, "*", n2, "=", multiplication(n1, n2))
elif operation == 4:
    print (n1, "/", n2, "=", division(n1, n2))
else:
    print("Invalid Input")

Select Operations
1. Addition 2. Subtraction 3. Multiplication 4. Division
Enter choice of operation 1/2/3/4: 2
Enter the First Number: 10
Enter the Second Number: 20
10.0 - 20.0 = -10.0